#--------------------------------------------------------------------------------
# Travis CI building configuration file for Linux Operating system
#                             created 2017-07-27
#--------------------------------------------------------------------------------

git:
  depth: 1

branches:
  only:
    - master

language: cpp
os: linux
dist: trusty


before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qt5-default qtbase5-dev qt5-qmake qttools5-dev-tools libqt5concurrent5 libqt5test5 qtmultimedia5-dev libqt5multimedia5-plugins libqt5multimediawidgets5 qt5-image-formats-plugins libasound2-dev libpulse-dev

script:
 - qmake CONFIG-=debug CONFIG+=release
 - make -s -j 4

